import 'dart:io';

import 'package:share_plus/share_plus.dart';

class ShareService {
  ShareService._();

  static final ShareService instance =
      ShareService._();

  Future<void> shareFile({
    required File file,
    String? subject,
    String? text,
  }) async {
    await Share.shareXFiles(
      [
        XFile(file.path),
      ],
      subject: subject,
      text: text,
    );
  }

  Future<void> shareExcel({
    required File excelFile,
  }) async {
    await Share.shareXFiles(
      [
        XFile(excelFile.path),
      ],
      subject: "Inventory Excel Report",
      text:
          "Inventory report generated from Inventory Controller Pro.",
    );
  }

  Future<void> sharePng({
    required File pngFile,
  }) async {
    await Share.shareXFiles(
      [
        XFile(pngFile.path),
      ],
      subject: "Inventory PNG Report",
      text:
          "Inventory report generated from Inventory Controller Pro.",
    );
  }

  Future<void> shareMultiple({
    required List<File> files,
  }) async {
    final List<XFile> xFiles =
        files
            .map(
              (e) => XFile(e.path),
            )
            .toList();

    await Share.shareXFiles(
      xFiles,
      subject: "Inventory Report",
      text:
          "Shared using Inventory Controller Pro.",
    );
  }

  Future<void> shareText({
    required String message,
  }) async {
    await Share.share(
      message,
    );
  }

  Future<void> shareInventorySummary({
    required int totalProducts,
    required int totalQuantity,
  }) async {
    final summary = '''

Inventory Summary

Total Products : $totalProducts

Total Quantity : $totalQuantity

Generated by Inventory Controller Pro

''';

    await Share.share(
      summary,
    );
  }
}